name: Build, Analyze, Scan
on: 
    push:
        branches:
            - main

jobs:
    build_analyze_scan:
        name: Build
        runs-on: ubuntu-latest  # [self-hosted] (use if running on a self-hosted runner)
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Set up Python 3.11
              uses: actions/setup-python@v2
              with:
                  python-version: 3.11

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            - name: Docker Build and Push
              run: |
                  docker-compose -f docker-compose.yaml build
                  docker tag webapp:latest frosty888/webapp:latest
                  echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
                  docker push frosty888/webapp:latest
              env:
                  DOCKER_CLI_ACI: 1
